# Generated by Django 5.1.4 on 2024-12-20 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_title1', models.CharField(max_length=50)),
                ('header_title2', models.CharField(max_length=50)),
                ('header_title3', models.CharField(max_length=50)),
                ('header_image', models.FileField(upload_to='image/')),
            ],
        ),
    ]
