# Generated by Django 5.1.4 on 2024-12-20 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tournaments_prize', models.CharField(max_length=50)),
                ('Tournaments_detail', models.CharField(max_length=50)),
                ('Tournaments_image', models.FileField(upload_to='image/')),
            ],
        ),
    ]
