# Generated by Django 5.0.6 on 2024-12-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tournaments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tournaments',
            new_name='Tournament',
        ),
    ]
