# Generated by Django 5.0.6 on 2024-12-21 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_tournaments_tournament'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name (Govt ID Proof)')),
                ('game_name', models.CharField(max_length=50)),
                ('unique_game_id', models.CharField(max_length=50)),
                ('team_id', models.IntegerField()),
            ],
        ),
    ]
