# Generated by Django 5.0.6 on 2024-12-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_teammember'),
    ]

    operations = [
        migrations.CreateModel(
            name='Winner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_team_image', models.FileField(upload_to='image/')),
                ('winner_team_name', models.CharField(max_length=50)),
                ('winner_team_played', models.CharField(max_length=50)),
                ('winner_team_game_win', models.CharField(max_length=50)),
            ],
        ),
    ]
