# Generated by Django 5.0.6 on 2024-12-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_winner'),
    ]

    operations = [
        migrations.AddField(
            model_name='winner',
            name='winner_team_mode',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
