# Generated by Django 5.0.6 on 2024-12-25 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_lastname',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
