# Generated by Django 5.0.6 on 2024-12-25 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_user_user_lastname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_phone',
        ),
    ]
